---

# ansible-playbook deploy.yml --syntax-check
# ansible -v all -m ping -e 'ansible_python_interpreter=/usr/bin/python3'
# ansible-playbook deploy.yml

- name: Set ansible_python_interpreter
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - { role: python_interpreter, tags: [always] }

- name: Deploy app
  hosts: all
  remote_user: web
  roles:
    - jasperf.laravel5deploy
  vars:
    laravel_strategy: git
    laravel_root_dir: /home/web/laravel
    laravel_repo: git@github.com:Larastudio/lslaravel.git
    laravel_composer_install: false
    ansible_ssh_user: web
