---

# ansible-playbook server.yml --syntax-check
# ansible -v all -m ping -e 'ansible_python_interpreter=/usr/bin/python3'
# ansible-playbook server.yml

- name: Set ansible_python_interpreter
  hosts: all
  gather_facts: false
  become: yes
  roles:
    - { role: python_interpreter, tags: [always] }


- name: Create a Web user with sudo access
  hosts: all
  remote_user: root
  tasks:
    - name: Web User
      user: 
        name: "{{web_user}}"
        # a hash can be manually created with: mkpasswd `gem install mkpasswd` and "mkpasswd -m sha-512 "password" | sed 's/\$/\\$/g'
        # here we use `pip install passlib` instead for automatic generation
        password: "{{ upassword | password_hash('sha512') }}"
        groups: # Empty by default, here we give it some groups
        - sudo
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/web  # Defaults to /home/<username>
        # https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
    - name: keys additions
      authorized_key: 
        user: "{{web_user}}"
        key: "{{github_keys}}"

- name: Install Docker, Docker Compose, UFW
  hosts: all
  remote_user: root
  roles:
    - geerlingguy.docker
    - weareinteractive.ufw
  vars: 
    # https://github.com/docker/compose/releases
    docker_compose_version: "1.23.2"
    docker_users:
      - web
    ufw_rules:
      - { port: 22, rule: allow, comment: 'Allow SSH' }
      - { port: 80, rule: allow }
      - { port: 443, rule: allow }
      - { from_ip: '127.0.0.1/8', comment: 'Allow localhost' }
      - { from_ip: '127.0.42.0/24', rule: deny }
    ufw_default_forward_policy: ACCEPT
    ufw_logging: full
    ufw_applications:
     - { name: "OpenSSH" }